### PR TITLE
Update dependencies for routing typescript

### PR DESCRIPTION
**Pull request by ektaghag-eaton**
Fixes 4881 .

#### Changes proposed in this Pull Request:

- Update dependencies to run routing typescript
- 
-

#### Screenshots / Screen Recording (if applicable)

-

#### To Test:

-

#### Any specific feedback you are looking for?

-

### CODE REVIEW

**Comment by JeffGreiner-eaton** [comment]
weird but the updated dependencies causing drawer issues

image

**Comment by ektaghag-eaton** [comment]
> weird but the updated dependencies causing drawer issues
> 
> image

Please pull lastet changes. [This commit](https://github.com/etn-ccis/blui-react-native-cli-templates/pull/102/commits/285a606ea7150be806b2d36bd484067b5ecf97ca) should fix it.

**Review by JeffGreiner-eaton — APPROVED** [review]
Looks good

**Comment by JeffGreiner-eaton** [comment]
Android running routing template
https://github.com/etn-ccis/blui-react-native-cli-templates/assets/119693939/ad47aad4-7c65-46ef-960f-375281ecd62f

**Pull request merged**
